language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - yarn install --frozen-lockfile
  - yarn test && codecov
  - bash <(curl -s https://codecov.io/bash) -t 6754916b-15c1-4e8a-a06f-a70d2d0eeb3e