os:
  - osx
language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - yarn install --frozen-lockfile
  - yarn lint
  - yarn test && codecov
  - bash <(curl -s https://codecov.io/bash)
  - yarn docs

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
